# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-13 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0002_auto_20190613_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forums',
            name='post_id',
        ),
    ]
