# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-17 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0003_assessment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessment',
            old_name='score',
            new_name='noscore',
        ),
        migrations.AddField(
            model_name='assessment',
            name='question',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessment',
            name='yesscore',
            field=models.IntegerField(default=0),
        ),
    ]
